version: '3.5'

services:
  bog-postgres-consaliotest:
    container_name: bog-postgres-consaliotest
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-orthos}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-orthos}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5451:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgweb-consalio:
    container_name: bog-pgweb-consaliotest
    image: sosedoff/pgweb
    restart: unless-stopped
    ports:
      - "5452:8081"
    environment:
      - DATABASE_URL=postgres://orthos:orthos@host.docker.internal:5451/postgres?sslmode=disable
    depends_on:
      - bog-postgres-consaliotest
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: